### ISSUE TITLE
Example RminerExample.java is having an error

### ISSUE THREAD

**Issue by dshoaibi** [osmarleandro/mining-refactorings-example#1]
I was not able to run the example on RminerExample.java.
I always have the following error. 

Console output:
SLF4J: Found binding in [jar:file:/Users/deemashoaibi/.m2/repository/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/deemashoaibi/.m2/repository/org/slf4j/slf4j-log4j12/1.7.30/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[main] INFO org.refactoringminer.util.GitServiceImpl - Cloning https://github.com/danilofes/refactoring-toy-example.git ...
[main] INFO org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl - Processing tmp/refactoring-toy-example 70b71b7fd3c5973511904c468e464d4910597928 ...
[main] WARN org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl - Ignored revision 05c1e773878bbacae64112f70964f4f2f7944398 due to error
java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.ASTParser.<init>(ASTParser.java:239)
	at org.eclipse.jdt.core.dom.ASTParser.newParser(ASTParser.java:134)
	at gr.uom.java.xmi.UMLModelASTReader.<init>(UMLModelASTReader.java:66)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.createModel(GitHistoryRefactoringMinerImpl.java:348)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:135)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:366)
	at br.com.rminer.example.RminerExample.detectAtCommit(RminerExample.java:35)
	at br.com.rminer.example.RminerExample.main(RminerExample.java:26)
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:39)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:377)
	at br.com.rminer.example.RminerExample.detectAtCommit(RminerExample.java:35)
	at br.com.rminer.example.RminerExample.main(RminerExample.java:26)
Caused by: java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.ASTParser.<init>(ASTParser.java:239)
	at org.eclipse.jdt.core.dom.ASTParser.newParser(ASTParser.java:134)
	at gr.uom.java.xmi.UMLModelASTReader.<init>(UMLModelASTReader.java:66)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.createModel(GitHistoryRefactoringMinerImpl.java:348)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:135)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:366)
	... 2 more

**Comment by osmarleandro** [comment]
Hi @dshoaibi, thanks for your issue. I fixed it into a new commit.
